# Generated by Django 3.2.9 on 2022-03-16 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0002_auto_20220315_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sort',
            name='id',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999999)]),
        ),
    ]
