# Generated by Django 4.0.3 on 2022-05-11 18:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0003_alter_sort_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortItem',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999999)])),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('image', models.CharField(max_length=2083, validators=[django.core.validators.MinLengthValidator(1)])),
                ('delete_flg', models.BooleanField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('sort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sort_items', to='sort.sort')),
            ],
        ),
    ]
