# Generated by Django 4.0.3 on 2022-05-12 18:30

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0005_user_remove_sort_user_id_like_sort_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='sortitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_time',
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='sort.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sort',
            name='play_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999999)]),
        ),
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(default=datetime.datetime(2022, 5, 12, 18, 30, 0, 21087, tzinfo=utc), max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='secret',
            field=models.CharField(default=datetime.datetime(2022, 5, 12, 18, 30, 8, 285682, tzinfo=utc), max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sort',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sortitem',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
    ]
