# Generated by Django 4.0.3 on 2022-05-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0006_rename_user_id_user_id_remove_sortitem_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sort',
            name='image',
        ),
    ]
