# Generated by Django 4.0.3 on 2022-05-13 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sort',
            name='play_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999999)]),
        ),
    ]
